# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
import typing
from typing import Any, Callable, Dict, List, Optional, Union
from cascade.spec.lazy_types import LazyResult
from cascade.spec.protocols import Connector, StateBackend, CachePolicy
def bytes(path: str) -> LazyResult: ...
def text(path: str, encoding: str = 'utf-8') -> LazyResult: ...
