import asyncio
import logging
from typing import Any, Optional, Dict

from cascade.spec.runtime.strategies import ExecutionStrategy, ExecutionContext
from cascade.spec.runtime.interfaces import Executor
from cascade.spec.physical.nodes import Token
from cascade.spec.physical.environment import EnvironmentDef

from cascade.vm.compute import BridgedComputeService
from cascade.vm.services.chronos import ChronosService
from cascade.vm.registry import CodeRegistry
from cascade.vm.machine import Machine
from cascade.vm.reactor import Reactor
from cascade.vm.kernel import PhysicsKernel
from cascade.vm.resource_registry import ResourceRegistry
from cascade.vm.memory import VolatileMemory
from cascade.vm.linker import Linker

from cascade.compiler.frontend import IRGenerator
from cascade.compiler.backend import Builder

logger = logging.getLogger(__name__)


class RuntimeHarness:
    """
    The 'Motherboard' for the VM instance.
    Responsible for assembling the physical environment, buses, and peripheral services
    required by the Machine to operate within the Runtime context.
    """

    def __init__(
        self,
        context: ExecutionContext,
        executor: Executor,
        code_registry: CodeRegistry,
    ):
        self.context = context

        # 1. Physical Buses (Queues)
        # VM <- Outside (Compute results, Timer events, User inputs)
        self.ingress_queue: asyncio.Queue = asyncio.Queue()
        # VM -> Outside (User Results)
        self.egress_queue: asyncio.Queue = asyncio.Queue()
        # VM -> Compute Service
        self.compute_queue: asyncio.Queue = asyncio.Queue()
        # VM -> Time Service
        self.chronos_queue: asyncio.Queue = asyncio.Queue()

        # 2. Signaling
        self.wakeup_event = asyncio.Event()

        # 3. Peripheral Services (Sidecars)
        # The BridgedComputeService adapts the VM's ComputeRequest protocol
        # to the Runtime's Executor protocol.
        self.compute_service = BridgedComputeService(
            executor=executor,
            store=context.object_store,
            registry=code_registry,
            inbound_queue=self.compute_queue,
            outbound_queue=self.ingress_queue,
            wakeup_event=self.wakeup_event,
        )

        self.chronos_service = ChronosService(
            inbound_queue=self.chronos_queue,
            outbound_queue=self.ingress_queue,
            wakeup_event=self.wakeup_event,
        )

        # 4. Resource Registry (The Environment)
        # Registers system-level resources that Kernel ICs (like egress, sleep) depend on.
        self.resource_registry = ResourceRegistry()
        self._register_system_resources()

    def _register_system_resources(self):
        self.resource_registry.register("system.egress_queue", self.egress_queue)
        self.resource_registry.register("system.compute_queue", self.compute_queue)
        self.resource_registry.register("system.chronos_queue", self.chronos_queue)
        self.resource_registry.register("system.object_store", self.context.object_store)
        # Note: 'system.event_bus' is usually expected by Observers.
        # We need to expose the bus from the context/engine if available.
        # Currently ExecutionContext doesn't carry the bus explicitly, but it might be
        # in active_resources or we might need to extend ExecutionContext.
        # For now, we leave it, assuming Observers might fail or we'll add it later.


class VMExecutionStrategy(ExecutionStrategy):
    """
    The Next-Gen Execution Strategy based on the Cascade VM (Physics Engine).

    It orchestrates the full lifecycle:
    1. Compile: Logical Graph -> Physical Assembly
    2. Link: Register executable code
    3. Bootstrap: Assemble the Machine and Harness
    4. Ignite: Inject initial energy
    5. Run: Drive the Machine loop and harvest results
    """

    def __init__(self, executor: Executor):
        self.executor = executor
        self.compiler_frontend = IRGenerator()
        self.compiler_backend = Builder()
        self.linker = Linker()

    async def execute(self, target: Any, context: ExecutionContext) -> Any:
        logger.info("VMStrategy: Starting execution cycle.")

        # --- Phase 1: Compilation ---
        # Transform the user's Logical Intent (LazyResult) into a Physical Assembly.
        logger.debug("VMStrategy: Compiling logical graph...")
        graph_ir_result = self.compiler_frontend.generate(target)
        graph_ir = graph_ir_result.ir
        
        # TODO: Construct EnvironmentDef from context.active_resources or resource_manager
        env_def = EnvironmentDef(resources=[]) 
        
        artifact = self.compiler_backend.build(graph_ir, environment=env_def)
        logger.debug("VMStrategy: Compilation complete.")

        # --- Phase 2: Linking ---
        # Register the executable code blocks (functions) generated by the frontend
        # into a CodeRegistry so the VM can find them by hash.
        logger.debug("VMStrategy: Linking code...")
        code_registry = CodeRegistry()
        for nid, code_hash in artifact.assembly.symbol_table.items():
            # The frontend generates a mapping of instance_hash -> executable
            # We need to map code_hash -> executable.
            # In the current simple model, instance_hash 1:1 code_hash for unique tasks,
            # but we should look up the executable from the frontend result using the node ID.
            # The frontend result `executables` is Dict[node_instance_hash, Callable].
            
            # Wait, symbol_table maps Physical ID -> Canonical Code Hash.
            # IRGenerator.executables maps Logical Node ID (current_node_instance_hash) -> Callable.
            # We need to bridge this.
            
            # For now, let's assume the IRGenerator provided executables keyed by the 
            # same hash used in the node definition if possible, OR we rely on the fact 
            # that we can resolve them.
            
            # Workaround: The frontend's `executables` map is keyed by `node_instance_hash`.
            # The `code_hash` in symbol table is `canonical_code_structure_hash`.
            # We need to register: registry[canonical_code_structure_hash] = Callable.
            
            # Let's iterate over the IR nodes to find the mapping between code_hash and callable.
            pass
        
        # Temporary Linking Logic (Naive):
        # We just register everything we found in the frontend generation result.
        # This part needs refinement to strictly follow the hash protocol.
        for node_ir in graph_ir.nodes:
            code_hash = node_ir.task.fingerprint.get("canonical_code_structure_hash")
            if code_hash and node_ir.current_node_instance_hash in graph_ir_result.executables:
                func = graph_ir_result.executables[node_ir.current_node_instance_hash]
                # Register if not exists (idempotent)
                if not code_registry.has(code_hash):
                    code_registry.register(code_hash, func)

        # --- Phase 3: Bootstrap ---
        # Assemble the physical machine.
        logger.debug("VMStrategy: Bootstrapping machine...")
        harness = RuntimeHarness(context, self.executor, code_registry)

        # 3.1 Kernel Construction
        # Link the physical nodes to their Kernel implementations (ICs)
        function_map = self.linker.link(artifact.assembly, code_registry)
        kernel = PhysicsKernel(function_map, harness.resource_registry)

        # 3.2 Reactor & Machine Construction
        memory = VolatileMemory()
        reactor = Reactor(
            graph=artifact.assembly.graph,
            memory=memory,
            kernel=kernel,
            ingress_queue=harness.ingress_queue,
        )
        machine = Machine(
            reactor=reactor,
            compute_service=harness.compute_service,
            chronos_service=harness.chronos_service,
            wakeup_event=harness.wakeup_event,
        )

        # --- Phase 4: Ignition ---
        # Inject initial potential energy (constants, pulses).
        logger.debug("VMStrategy: Igniting reactor...")
        
        # We need to materialize constants into the ObjectStore just like the EventDrivenRunner does.
        # This logic should arguably be in a shared helper or the Reactor itself if generalized.
        for node in artifact.assembly.graph.nodes.values():
            if hasattr(node, "initial_tokens") and node.initial_tokens > 0 and node.id.startswith("const."):
                 payload = node.initial_payload
                 # TODO: Check if already Ref, if not put into store.
                 # For now, simplistic check:
                 if payload is not None and not hasattr(payload, "uri"): # check for Ref duck typing
                     meta = {}
                     if isinstance(payload, (int, float, bool, str)) and len(str(payload)) < 256:
                         meta["scalar_value"] = payload
                     node.initial_payload = context.object_store.put(payload, metadata=meta)

        reactor.prime(genesis_trace={"rid": context.run_id})

        # --- Phase 5: Run Loop & Harvesting ---
        logger.debug("VMStrategy: Running...")
        
        # Start the machine in background
        machine_task = asyncio.create_task(machine.run())
        
        try:
            # Main Harvesting Loop
            # We need to identify which Egress node corresponds to our target result.
            # The Manifest has `exit_points` which maps Logical UUID -> Physical Egress ID.
            
            target_uuid = getattr(target, "_uuid", None)
            if not target_uuid and isinstance(target, list) and target:
                 # Handle list targets (e.g. gather). For now assume single target for skeleton.
                 target_uuid = target[0]._uuid
            
            if not target_uuid:
                # If we can't determine target, just run until stop?
                # Or maybe the target IS the graph.
                pass

            # Determine expected egress ID
            # target_egress_id = artifact.manifest.exit_points.get(target_uuid)
            
            # Wait for completion (Simplified for Skeleton)
            # In reality, we'd wait for specific Egress tokens.
            await machine_task
            
            return "Execution Complete (Skeleton Result)"

        except Exception as e:
            logger.error(f"VM execution failed: {e}")
            raise
        finally:
            # Ensure machine is stopped
            if not machine_task.done():
                reactor.shutdown_event.set()
                await asyncio.wait([machine_task], timeout=2.0)