# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
from typing import Any, Callable, Dict, List, Optional, Union
from cascade.spec.lazy_types import LazyResult
def bytes(path: str, content: bytes) -> 'LazyResult[Any]':
"""

    """

def text(path: str, content: str, encoding: str = 'utf-8') -> 'LazyResult[Any]':
"""

    """

