# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
from typing import Any, Callable, Dict, List, Optional, Union
from cascade.spec.lazy_types import LazyResult
def write(text: str) -> LazyResult:
    """
    Writes text to standard output.
    """
