# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
from cascade.spec.protocols import LazyFactory
delete: LazyFactory
get: LazyFactory
post: LazyFactory
put: LazyFactory
request: LazyFactory
