# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
import typing  # noqa: F401
from typing import Any, Callable, Dict, List, Optional, Union  # noqa: F401
from cascade.spec.lazy_types import LazyResult  # noqa: F401
from cascade.spec.protocols import Connector, StateBackend, CachePolicy  # noqa: F401

def delete(
    url: str, headers: typing.Optional[typing.Dict[str, str]] = None
) -> LazyResult: ...
def get(
    url: str,
    params: typing.Optional[typing.Dict[str, str]] = None,
    headers: typing.Optional[typing.Dict[str, str]] = None,
) -> LazyResult: ...
def post(
    url: str,
    json: typing.Optional[typing.Any] = None,
    data: typing.Optional[typing.Any] = None,
    files: typing.Optional[typing.Dict[str, str]] = None,
    headers: typing.Optional[typing.Dict[str, str]] = None,
    params: typing.Optional[typing.Dict[str, str]] = None,
) -> LazyResult: ...
def put(
    url: str,
    json: typing.Optional[typing.Any] = None,
    data: typing.Optional[typing.Any] = None,
    files: typing.Optional[typing.Dict[str, str]] = None,
    headers: typing.Optional[typing.Dict[str, str]] = None,
) -> LazyResult: ...
def request(
    url: str,
    method: str = "GET",
    params: typing.Optional[typing.Dict[str, str]] = None,
    json: typing.Optional[typing.Any] = None,
    data: typing.Optional[typing.Any] = None,
    files: typing.Optional[typing.Dict[str, str]] = None,
    headers: typing.Optional[typing.Dict[str, str]] = None,
) -> LazyResult: ...
