from cascade.spec.physical.topology import BipartiteGraph, Channel
from cascade.spec.physical.nodes import PhysicsNode, PhysicsFuncNode, PhysicsDataNode
from ..expander import SubGraph


class WiringError(ValueError):
    pass


class ArchitectureViolationError(RuntimeError):
    pass


class WiringHarness:
    def __init__(self, graph: BipartiteGraph):
        self.graph = graph
        self._locked = False

    def lock(self) -> None:
        """Locks the harness, preventing any further node additions."""
        self._locked = True

    def add_node(self, node: PhysicsNode) -> None:
        if self._locked:
            raise ArchitectureViolationError(
                "Cannot add nodes during the Wiring phase. "
                "Node creation is restricted to the Expansion phase."
            )
        if node.id in self.graph.nodes:
            raise WiringError(f"Node ID collision: '{node.id}' is already registered.")
        self.graph.nodes[node.id] = node

    def add_subgraph(self, subgraph: SubGraph) -> None:
        if self._locked:
            raise ArchitectureViolationError(
                "Cannot add subgraphs during the Wiring phase. "
                "Node creation is restricted to the Expansion phase."
            )
        for node in subgraph.nodes.values():
            # We use setdefault logic or simple overwrite?
            # SubGraphs should have unique IDs generated by generator.
            if node.id in self.graph.nodes:
                raise WiringError(
                    f"Subgraph Node ID collision: '{node.id}' is already registered."
                )
            self.graph.nodes[node.id] = node

        # We extend channels directly; SubGraph channels are assumed to be internal and valid
        self.graph.channels.extend(subgraph.channels)

    def connect(
        self,
        source_id: str,
        source_port: str,
        target_id: str,
        target_port: str,
    ) -> None:
        # 1. Existence Check
        if source_id not in self.graph.nodes:
            raise WiringError(f"Source node '{source_id}' not found in graph.")
        if target_id not in self.graph.nodes:
            raise WiringError(f"Target node '{target_id}' not found in graph.")

        src_node = self.graph.nodes[source_id]
        tgt_node = self.graph.nodes[target_id]

        # 2. Port Validation
        # For FuncNodes, ports must be explicitly defined.
        if isinstance(src_node, PhysicsFuncNode):
            if source_port not in src_node.output_ports:
                raise WiringError(
                    f"FuncNode '{source_id}' has no output port '{source_port}'. "
                    f"Available: {list(src_node.output_ports.keys())}"
                )
        elif isinstance(src_node, PhysicsDataNode):
            # DataNodes usually imply 'out', but we allow loose string matching for now
            # as DataNodes don't strictly define ports in the current spec implementation
            pass

        if isinstance(tgt_node, PhysicsFuncNode):
            if target_port not in tgt_node.input_ports:
                raise WiringError(
                    f"FuncNode '{target_id}' has no input port '{target_port}'. "
                    f"Available: {list(tgt_node.input_ports.keys())}"
                )
        elif isinstance(tgt_node, PhysicsDataNode):
            # DataNodes typically expect 'in'
            pass

        # 3. Connect
        channel = Channel(
            source_node_id=source_id,
            source_port=source_port,
            target_node_id=target_id,
            target_port=target_port,
        )
        self.graph.channels.append(channel)
