# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
import typing  # noqa: F401
from typing import Any, Callable, Dict, List, Optional, Union  # noqa: F401
from cascade.spec.lazy_types import LazyResult  # noqa: F401
from cascade.spec.protocols import Connector, StateBackend, CachePolicy  # noqa: F401

def add(path: str) -> LazyResult:
    """
    Creates a Cascade workflow to add a local file to IPFS and get its CID.
    """
def cat(cid: str) -> LazyResult:
    """
    Creates a Cascade workflow to retrieve the contents of a file from IPFS.

    This is a composition of `cs.http.post` and a parsing task.
    """
