# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
from typing import Any, Callable, Dict, List, Optional, Union
from cascade.spec.lazy_types import LazyResult
def add(path: str) -> LazyResult:
    """
    Creates a Cascade workflow to add a local file to IPFS and get its CID.
    """
def cat(cid: str) -> LazyResult:
    """
    Creates a Cascade workflow to retrieve the contents of a file from IPFS.

    This is a composition of `cs.http.post` and a parsing task.
    """
