from dataclasses import dataclass, field
from typing import Any, Dict
from cascade.spec.ports import PortDef


@dataclass
class Token:
    payload: Any
    """The actual data being transferred (Business Value)."""

    tag: str = "default"
    """Routing tag used by Channels to filter tokens (Control Signal)."""

    trace: Dict[str, Any] = field(default_factory=dict)
    """
    Metadata accumulator for observability and context propagation.
    Contains timestamp, source_id, retry_counts, etc.
    """


@dataclass
class PhysicsNode:
    id: str
    """
    The unique physical ID for this node instance within a compiled graph.
    Naming Convention: Path-like, e.g., 'node_a.bleach', 'canonical.resource.gpu'.
    Generated by the compiler to ensure uniqueness and aid in debugging.
    """

    name: str
    """Human-readable name for debugging and visualization."""


@dataclass
class PhysicsDataNode(PhysicsNode):
    capacity: int = 1
    """Maximum number of tokens this node can hold simultaneously."""

    initial_tokens: int = 0
    """Number of tokens to pre-fill at reactor startup (Potential Energy)."""

    initial_payload: Any = None
    """The payload to use for pre-filled tokens."""


@dataclass
class PhysicsFuncNode(PhysicsNode):
    input_ports: Dict[str, PortDef] = field(default_factory=dict)
    """Map of port_name -> PortDef."""

    output_ports: Dict[str, PortDef] = field(default_factory=dict)
    """Map of port_name -> PortDef."""
