# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
from cascade.spec.protocols import LazyFactory
from typing import Any

Namespace = Any

local: Namespace
s3: Namespace
stdin: Namespace
stdout: Namespace
