# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
from typing import Any, Callable, Dict, List, Optional, Union
from cascade.spec.lazy_types import LazyResult
from . import local as local
from . import s3 as s3
from . import stdin as stdin
from . import stdout as stdout
