# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
from . import local as local
from . import s3 as s3
from . import stdin as stdin
from . import stdout as stdout
