# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
from typing import Any, Callable, Dict, List, Optional, Union
from cascade.spec.lazy_types import LazyResult

# --- Known SDK Exports ---
from cascade.context import get_current_context
from cascade.flow import pipeline, sequence
from cascade.graph.serialize import from_json, to_json
from cascade.runtime.engine import Engine
from cascade.runtime.events import Event
from cascade.runtime.exceptions import DependencyMissingError
from cascade.spec.constraint import with_constraints
from cascade.spec.lazy_types import LazyResult
from cascade.spec.resource import inject, resource
from cascade.spec.routing import Router
from cascade.spec.task import task
from cascade.testing import override_resource
from cascade.tools.cli import create_cli
from cascade.tools.preview import dry_run
from cascade.tools.visualize import visualize

# --- Locally Defined Exports ---
Env: Callable[..., Any]
Param: Callable[..., Any]
run: Callable[..., Any]

# --- Discovered Providers ---
def dict(**kwargs) -> 'LazyResult[Any]':
"""
    Creates a dictionary from keyword arguments.
    Useful for composing dynamic contexts in the graph.
    """

def format(template: str, *args, **kwargs) -> 'LazyResult[Any]':
"""
    Formats a string using Python's str.format syntax.

    Usage:
        cs.format("Hello, {name}!", name=cs.Param("name"))
    """

def load_yaml(path: str) -> 'LazyResult[Any]':
"""
    Asynchronously reads and parses a YAML file.
    """

def lookup(source: Dict[str, Any], key: str) -> 'LazyResult[Any]':
"""
    Executes a dot-separated lookup in the provided dictionary.
    """

def recv(topic: str, timeout: Optional[float] = None, connector: cascade.spec.protocols.Connector = Inject(resource_name='_internal_connector')) -> 'LazyResult[Any]':
"""
    Pauses execution until a signal is received on the given topic.
    """

def shell(command: str, check: bool = True) -> 'LazyResult[Any]':
"""
    Asynchronously executes a shell command and returns its stdout.
    """

def sql(query: str, db: str, params: Optional[Dict[str, Any]] = None) -> 'LazyResult[Any]':
"""
    Factory function exposed as cs.sql.

    Args:
        query: The SQL query string.
        db: The name of the resource providing the SQLAlchemy connection/engine.
        params: Optional parameters for the query.

    Returns:
        A LazyResult that resolves to the query results.
    """

def subflow(path: str, target: str, params: Optional[Dict[str, Any]] = None) -> 'LazyResult[Any]':
"""
    Dynamically loads a workflow from a file and executes it in an isolated engine.

    Args:
        path: Path to the Python file containing the workflow definition.
        target: The variable name in the module that holds the LazyResult (or callable).
        params: Parameters to inject into the sub-workflow.
    """

def template(template_string: str, context: Optional[Dict[str, Any]] = None, **kwargs) -> 'LazyResult[Any]':
"""
    Renders a Jinja2 template string with the provided context.

    Args:
        template_string: The Jinja2 template string.
        context: A dictionary of context variables.
        **kwargs: Additional context variables passed as keyword arguments.

    Returns:
        The rendered string.
    """

def wait(delay: Union[float, int]) -> 'LazyResult[Any]':
"""
    Asynchronously waits for a specified duration.
    This is a non-blocking operation.

    Args:
        delay: The duration to wait in seconds.
    """


from . import fs as fs
from . import http as http
from . import io as io
from . import ipfs as ipfs
from . import read as read
from . import write as write
