# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
import typing
from typing import Any, Callable, Dict, List, Optional, Union
from cascade.spec.lazy_types import LazyResult
from cascade.spec.protocols import Connector, StateBackend, CachePolicy

# --- Known SDK Exports ---
from cascade.context import get_current_context as get_current_context
from cascade.flow import pipeline as pipeline, sequence as sequence
from cascade.graph.serialize import from_json as from_json, to_json as to_json
from cascade.runtime.engine import Engine as Engine
from cascade.runtime.events import Event as Event
from cascade.runtime.exceptions import DependencyMissingError as DependencyMissingError
from cascade.spec.constraint import with_constraints as with_constraints
from cascade.spec.lazy_types import LazyResult as LazyResult
from cascade.spec.resource import inject as inject, resource as resource
from cascade.spec.routing import Router as Router
from cascade.spec.task import task as task
from cascade.testing import override_resource as override_resource
from cascade.tools.cli import create_cli as create_cli
from cascade.tools.preview import dry_run as dry_run
from cascade.tools.visualize import visualize as visualize

# --- Locally Defined Exports ---
def Env(name: str, default: Any = None, description: str = '') -> LazyResult:
    """
    定义一个环境变量依赖。
    """
def Param(name: str, default: Any = None, type: Any = ..., description: str = '') -> LazyResult:
    """
    定义一个工作流参数。

    它会向工作流上下文注册其元数据，并返回一个 LazyResult，
    该 LazyResult 在执行时会从用户提供的参数中提取值。
    """
def run(target: LazyResult, params: typing.Optional[typing.Dict[str, typing.Any]] = None, system_resources: typing.Optional[typing.Dict[str, typing.Any]] = None, log_level: str = 'INFO', log_format: str = 'human', connector: typing.Optional[Connector] = None, state_backend: typing.Union[str, typing.Callable[[str], StateBackend], None] = None) -> LazyResult:
    """
    Runs a Cascade workflow with a default engine configuration.

    Args:
        state_backend: A URI string (e.g. "redis://localhost") or a factory function
                       that accepts a run_id and returns a StateBackend.
    """

# --- Discovered Providers ---
from . import fs as fs
from . import http as http
from . import io as io
from . import ipfs as ipfs
from . import read as read
from . import write as write

def dict(**kwargs) -> LazyResult:
    """
    Creates a dictionary from keyword arguments.
    Useful for composing dynamic contexts in the graph.
    """
def format(template: str, *args, **kwargs) -> LazyResult:
    """
    Formats a string using Python's str.format syntax.

    Usage:
        cs.format("Hello, {name}!", name=cs.Param("name"))
    """
def load_yaml(path: str) -> LazyResult:
    """
    Asynchronously reads and parses a YAML file.
    """
def lookup(source: typing.Dict[str, typing.Any], key: str) -> LazyResult:
    """
    Executes a dot-separated lookup in the provided dictionary.
    """
def recv(topic: str, timeout: typing.Optional[float] = None, connector: Connector = ...) -> LazyResult:
    """
    Pauses execution until a signal is received on the given topic.
    """
def shell(command: str, check: bool = True) -> LazyResult:
    """
    Asynchronously executes a shell command and returns its stdout.
    """
def sql(query: str, db: str, params: typing.Optional[typing.Dict[str, typing.Any]] = None) -> LazyResult:
    """
    Factory function exposed as cs.sql.

    Args:
        query: The SQL query string.
        db: The name of the resource providing the SQLAlchemy connection/engine.
        params: Optional parameters for the query.

    Returns:
        A LazyResult that resolves to the query results.
    """
def subflow(path: str, target: str, params: typing.Optional[typing.Dict[str, typing.Any]] = None) -> LazyResult:
    """
    Dynamically loads a workflow from a file and executes it in an isolated engine.

    Args:
        path: Path to the Python file containing the workflow definition.
        target: The variable name in the module that holds the LazyResult (or callable).
        params: Parameters to inject into the sub-workflow.
    """
def template(template_string: str, context: typing.Optional[typing.Dict[str, typing.Any]] = None, **kwargs) -> LazyResult:
    """
    Renders a Jinja2 template string with the provided context.

    Args:
        template_string: The Jinja2 template string.
        context: A dictionary of context variables.
        **kwargs: Additional context variables passed as keyword arguments.

    Returns:
        The rendered string.
    """
def wait(delay: typing.Union[float, int]) -> LazyResult:
    """
    Asynchronously waits for a specified duration.
    This is a non-blocking operation.

    Args:
        delay: The duration to wait in seconds.
    """
