from typing import Protocol, Any, Dict, Optional
from ..physical.object import Ref


class ObjectStore(Protocol):
    def put(self, obj: Any, metadata: Optional[Dict[str, Any]] = None) -> Ref: ...

    def get(self, ref: Ref) -> Any: ...

    def peek(self, ref: Ref) -> Ref: ...

    def delete(self, ref: Ref) -> None: ...
