# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
from typing import Any, Callable, Dict, List, Optional, Union
from cascade.spec.lazy_types import LazyResult
def exists(path: str) -> LazyResult[Any]:
    """

        """

def read_bytes(path: str) -> LazyResult[Any]:
    """

        """

def read_text(path: str, encoding: str = 'utf-8') -> LazyResult[Any]:
    """

        """

def write_bytes(path: str, content: bytes) -> LazyResult[Any]:
    """

        """

def write_text(path: str, content: str, encoding: str = 'utf-8') -> LazyResult[Any]:
    """

        """

