# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
from cascade.spec.protocols import LazyFactory
exists: LazyFactory
read_bytes: LazyFactory
read_text: LazyFactory
write_bytes: LazyFactory
write_text: LazyFactory
