import pytest
from unittest.mock import MagicMock
from cascade.spec.task import task
from cascade.compiler.frontend import Frontend
from cascade.compiler.backend import Backend
from cascade.spec.ir.models import GraphIR, NodeIR, TaskDef
from cascade.spec.fingerprint import Fingerprint
from cascade.spec.blueprint import Call

def test_frontend_returns_compilation_result_with_symbol_table():
    """
    验证 Frontend.compile 返回的是 CompilationResult 对象，
    并且包含正确的 symbol_table。
    """
    @task
    def my_func(): pass

    # RED 阶段：Frontend.compile 目前返回 GraphIR，没有 symbol_table 属性
    result = Frontend.compile(my_func())
    
    # 检查类型 (不直接 import 类以避免 ImportError 阻断测试运行，依靠鸭子类型或类名检查)
    assert type(result).__name__ == "CompilationResult", \
        f"Expected CompilationResult, got {type(result).__name__}"

    assert hasattr(result, "symbol_table"), "Result missing symbol_table"
    assert hasattr(result, "ir"), "Result missing ir"
    
    # 验证 Symbol Table 内容
    symbol_table = result.symbol_table
    assert len(symbol_table) == 1
    
    # 获取唯一的 key (structure_hash)
    hash_key = list(symbol_table.keys())[0]
    
    # 验证 value 是原始函数
    assert symbol_table[hash_key] == my_func.func

def test_backend_populates_structure_hash_in_blueprint():
    """
    验证 Backend 在生成 Blueprint 时，从 NodeIR 的 definition 中读取
    current_code_structure_hash 并写入指令。
    """
    # 构造一个带有 structure_hash 的 NodeIR
    expected_hash = "test_hash_123"
    fp = Fingerprint.from_dict({"current_code_structure_hash": expected_hash})
    task_def = TaskDef(name="test_task", args=[], fingerprint=fp)
    node = NodeIR(current_node_instance_hash="n1", definition=task_def, kwargs={})
    
    graph = GraphIR(nodes=[node], edges=[])
    plan = [["n1"]]
    
    # Backend.compile 应该读取这个 hash 并放入 Blueprint
    blueprint = Backend.compile(graph, plan)
    
    assert len(blueprint.instructions) == 1
    instr = blueprint.instructions[0]
    assert isinstance(instr, Call)
    
    # RED 阶段失败点：instr 没有 structure_hash 属性
    if not hasattr(instr, "structure_hash"):
        pytest.fail("Instruction generated by Backend missing 'structure_hash' attribute")
        
    assert instr.structure_hash == expected_hash