# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
import typing  # noqa: F401
from typing import Any, Callable, Dict, List, Optional, Union  # noqa: F401
from cascade.spec.lazy_types import LazyResult  # noqa: F401
from cascade.spec.protocols import Connector, StateBackend, CachePolicy  # noqa: F401

def read_line(*_args) -> LazyResult:
    """
    Reads a single line from standard input.
    Accepts positional arguments to allow data dependencies for ordering.
    """
