# This file is auto-generated by scripts/generate_stubs.py.
# Do not edit this file directly.
from typing import Any, Callable, Dict, List, Optional, Union
from cascade.spec.lazy_types import LazyResult
def read_line(*_args) -> LazyResult[Any]:
    """
        Reads a single line from standard input.
        Accepts positional arguments to allow data dependencies for ordering.
        """

