from typing import Protocol, Dict, Union, Any

class ResourceManager(Protocol):
    async def acquire(self, requirements: Dict[str, Union[int, float]]) -> None: ...
    async def release(self, requirements: Dict[str, Union[int, float]]) -> None: ...

class ConstraintManager(Protocol):
    def check_permission(self, task_shim: Any) -> bool: ...
    def get_extra_requirements(self, task_shim: Any) -> Dict[str, Any]: ...